apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
  bucket: <<your-s3-bucket-name-here>>
  endpoint: <<your-s3-endpoint-here>>
  aws_access_key_id: <<your-aws-access-key-id-here>>
  aws_secret_access_key: <<your-aws-secret-access-key-here>>
